### ISSUE TITLE
how to open the log page

### ISSUE THREAD

**Issue by hkbhatia** [aaron-artille/gumshoe#6]
i am unable to open the log page please help with the same?

**Comment by aaron-artille** [comment]
Please see https://github.com/aaron-artille/gumshoe/issues/7.

For now, you can input `gselog` (or whatever your pass code is if you changed it) in standard text or password inputs that don't prevent default behavior, e.g. the Facebook login form or other forms that Gumshoe still successfully monitors these days.

**Comment by aaron-artille** [comment]
Please see https://github.com/aaron-artille/gumshoe/issues/7.

For now, you can input `gselog` (or whatever your pass code is if you changed it) in standard text or password inputs that don't prevent default behavior, e.g. the Facebook login form or other forms that Gumshoe still successfully monitors these days.
